// Generated by https://quicktype.io

export interface Aduanas {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface GUERRERO {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface CDMX {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface COAHUILA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface NUEVO_LEON {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface TAMAULIPAS  {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface QUINTANA_ROO {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface BAJA_CALIFORNIA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface BAJA_CALIFORNIA_SUR {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface MEXICO {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface QUERETARO {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface AGUASCALIENTES {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface OAXACA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface VERACRUZ {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface SONORA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface MICHOACAN {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface YUCATAN {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface JALISCO {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface GUANAJUATO {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface TABASCO {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface COLIMA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface CAMPECHE {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface PUEBLA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface CHIHUAHUA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface CHIAPAS {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}

export interface SINALOA {
    id:                 number;
    estado:             string;
    nombre:             string;
    telefono:           string;
    horario_sem:        string;
    horario_fin:        string;
    direccion:          string;
    tipo:               string;
    agentes:            string;
}


